# Schema for the configuration files of the Linkit module.

linkit.linkit_profile.*:
  type: config_entity
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
    description:
      type: string
    attributes:
      type: sequence
      sequence:
        type: mapping
        mapping:
          id:
            type: string
          weight:
            type: integer
    matchers:
      type: sequence
      sequence:
        type: linkit.matcher

linkit.matcher:
  type: mapping
  mapping:
    id:
      type: string
    uuid:
      type: string
    data:
      type: linkit.matcher.[%parent.id]
    weight:
      type: integer

linkit.matcher.*:
  type: mapping
  label: 'Matcher settings'

linkit.matcher.entity:
  type: mapping
  mapping:
    result_description:
      type: string
    bundles:
      type: sequence
      sequence:
        type: string
      nullable: true
    group_by_bundle:
      type: boolean

linkit.matcher.entity:*:
  type: linkit.matcher.entity

linkit.matcher.entity:node:
  type: linkit.matcher.entity
  mapping:
    include_unpublished:
      type: boolean
