# Schema for the configuration files of the Linkit module.

linkit.linkit_profile.*:
  type: config_entity
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
    description:
      type: string
    attributes:
      type: sequence
      sequence:
        type: linkit.attribute
    matchers:
      type: sequence
      sequence:
        type: linkit.matcher

linkit.attribute:
  type: mapping
  mapping:
    id:
      type: string
    data:
      type: linkit.attribute.[%parent.id]
    weight:
      type: integer

linkit.attribute.*:
  type: mapping
  label: 'Attribute settings'

linkit.attribute.target:
  type: linkit.attribute
  mapping:
    widget_type:
      type: string

linkit.matcher:
  type: mapping
  mapping:
    id:
      type: string
    uuid:
      type: string
    data:
      type: linkit.matcher.[%parent.id]
    weight:
      type: integer

linkit.matcher.*:
  type: mapping
  label: 'Matcher settings'

linkit.matcher.entity:
  type: mapping
  mapping:
    result_description:
      type: string
    bundles:
      type: sequence
      sequence:
        type: string
      nullable: true
    group_by_bundle:
      type: boolean

linkit.matcher.entity:*:
  type: linkit.matcher.entity

linkit.matcher.entity:node:
  type: linkit.matcher.entity
  mapping:
    include_unpublished:
      type: boolean
